src/App.tsx
src/components/KaKaoLogin/index.tsx
src/components/KaKaoLogin/styles.ts
src/pages/KaKao/index.tsx
src/pages/KaKao/styles.ts
src/pages/Main/index.tsx

> 카카오 소셜 로그인 연동 작업입니다.
<br/>
<br/>
> 로그인 전 버튼
> 로그인 화면 (동의)
<br/>
> 받은 code값을 Service server로 전송하여, accessToken 생성 후 다시 Client로 받게 됩니다.
<br/>

카카오 소셜 로그인

---

src/pages/MyProfile/index.tsx

> 기존 프로필 등록 페이지에서 이미지 추가 버튼 클릭 시 추가 안 되던 문제 해결
<br/>
> deep copy 적용 및 dependency array 수정
<br/>
> .
<br/>
> .
<br/>
> .

refactor: 프로필 등록 페이지 이미지 추가 에러 해결

---

src/components/CalendarComponent/index.tsx
src/pages/Posting/index.tsx

> 게시글 등록 페이지
> 1. date click 이벤트 처리
> 2. alert 로직 추가
<br/>
> 없음
<br/>
> date 클릭 전
> date 클릭 시 calendar 사라짐
> 게시글 등록 버튼 클릭 시 alert 추가
> alert 확인 클릭 시 이전 페이지로 이동
<br/>
<br/>

게시글 등록 페이지 - date click 이벤트 처리 및 alert 로직 추가

---

src/api/CommentAPI.ts
src/api/ExhibitionAPI.ts
src/api/FileAPI.ts
src/api/MatchingAPI.ts
src/api/PostingAPI.ts
src/services/HttpClient.ts

> 기능 단위 및 api 명세에 따른 모듈화를 위해, 각 api 별 API template 작성
<br/>
> Service/HttpClient.ts 내에 {header} 부분 변경
> (SERVER_BASE_URL -> .env 파일 내용으로 변경)
<br/>
<br/>
<br/>

API template 작성

---

package-lock.json
package.json
src/App.tsx
src/api/CommentAPI.ts
src/api/ExhibitionAPI.ts
src/api/FileAPI.ts
src/api/MatchingAPI.ts
src/api/PostingAPI.ts
src/components/Login/GoogleLoginButton/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/pages/Posting/index.tsx
src/recoil/atom/AccessToken.ts

> 구글 소셜 로그인 accessToken, refreshToken 관리
> accessToken은 recoil 전역 상태로, refreshToken은 쿠키로 관리
<br/>
> atom 추가.
> react-cookie 라이브러리 추가 (`npm i` 필요)
> (8/2 워크샵 논의 완료) .env 파일 수정
<br/>
<br/>
> accessToken 만료 시, refreshToken으로 검증하여 새로운 accessToken 받아오는 로직은 백엔드 상의 후 바로 추가 예정임.
<br/>

구글 소셜 로그인 accessToken, refreshToken 관리

---

src/App.tsx
src/api/PostingAPI.ts
src/components/Common/Header/index.tsx
src/components/Login/GoogleLoginButton/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/hooks/useIsLogin.tsx
src/recoil/atom/AccessToken.ts
src/services/HttpClient.ts

> 구글 소셜 로그인
<br/>
> 1. .env 파일 수정되었습니다. (슬랙 참고)
> 2. 보안 이슈로 accessToken은 recoil 상태 관리, refreshToken은 Cookie로 저장했습니다.
> 3. 상태관리 atom 파일 추가되었습니다.
> 4. accessToken 만료 시 axios interceptors로 refreshtoken 전송하여 재발급 받도록 했습니다.
<br/>
> ![image](https://github.com/hibit-team/hibit-frontend/assets/77184523/e6b1d740-bbe3-4db9-aeb9-ac472786e3b0)
> ***로그인 여부 판단할 때 이 훅으로 사용하면 됩니다.***
<br/>
<br/>

Google Login

---

src/App.tsx
src/components/Common/Header/index.tsx
src/components/GlobalModal/index.tsx
src/components/MatchPost/PostArticle/index.tsx
src/components/MatchPost/PostReplySection/index.tsx
src/components/MatchPost/PostReplySection/styles.ts
src/components/Matching/FilterButton/index.tsx
src/components/Matching/MatchingContainer/styles.ts
src/hooks/MatchingPost/useDeleteMatchingPostMutation.ts
src/hooks/MatchingPost/useDeleteReplyMutation.ts
src/hooks/MatchingPost/useGetInviteModalList.ts
src/hooks/MatchingPost/usePostMatchingArticleLikeMutation.ts
src/hooks/MatchingPost/usePostReplyLikeMutation.ts
src/hooks/MatchingPost/usePostSecondaryReplyInputMutation.ts
src/hooks/MatchingPost/useUpdateReplyTextMutation.ts
src/hooks/MatchingPost/useUpdateStateAndPostUserList.ts
src/pages/Main/index.tsx
src/pages/MatchPost/index.tsx
src/pages/MobileLanding/index.tsx
src/pages/MobileLanding/styles.ts
src/pages/OtherProfile/index.tsx

>  댓글작성 인가처리 관련 로직 수정 및 세부 기능 작업 
<br/>
>
1.  if(isLoggedIn && isProfilRegistered === 1) 인 경우 댓글 작성 가능 
2. 게시글 작성자 및 댓글 작성 유저 프로필 클릭시 타인프로필 페이지로 이동 추가 
3. 404페이지 UI 기반 모바일 인포페이지 추가 (데스크탑 사용 유도)
<br/>
> X
<br/>
>  X
<br/>
> X

게시글내부페이지 세부 추가 작업 

---

src/api/MatchingAPI.ts
src/api/OtherprofileAPI.ts
src/api/PostingAPI.ts
src/assets/data/alarm/tmpAlarmData.ts
src/components/Alarm/Accept/index.tsx
src/components/Alarm/Comment/index.tsx
src/components/Alarm/CommentHeart/index.tsx
src/components/Alarm/Invitation/index.tsx
src/components/Alarm/Openchat/index.tsx
src/components/Alarm/Recomment/index.tsx
src/components/Alarm/Refuse/index.tsx
src/components/Alarm/Remind/index.tsx
src/interfaces/Alarm/IAlarm.ts
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/OtherProfile/index.tsx
src/pages/OtherProfile/styles.ts
src/pages/Posting/PostPosting/index.tsx

> otherprofile, 알림 CTA 반영
<br/>
<br/>
<br/>
<br/>

otherprofile, 알림 CTA 반영

---

src/api/LoginAPI.ts
src/components/Common/Footer/intex.tsx
src/components/Common/Header/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/components/Main/MatchIntros/index.tsx
src/components/Main/MatchIntros/styles.ts
src/hooks/useLoginInfo.tsx
src/pages/MyProfile/PostMyProfile/index.tsx
src/services/HttpClient.ts

> Footer 매뉴얼, 이용약관 CTA 추가
<br/>
<br/>
<br/>
<br/>

Footer 매뉴얼, 이용약관 CTA 추가

---

src/App.tsx
src/components/GlobalModal/index.tsx
src/hooks/useLoginInfo.tsx
src/recoil/atom/LoginInfoState.ts

feat: 로그인 해결

---

src/components/Alarm/index.tsx
src/components/Common/Header/index.tsx
src/components/GlobalModal/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/components/MatchPost/PostLabel/index.tsx
src/components/MatchPost/PostReplySection/index.tsx
src/components/Matching/FilterButton/index.tsx
src/components/Matching/SearchBar/index.tsx
src/components/Matching/SearchBar/styles.ts
src/hooks/useLoginInfo.tsx
src/pages/Main/index.tsx
src/pages/MatchPost/index.tsx
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/OtherProfile/index.tsx
src/recoil/atom/LoginInfoState.ts

refactor/QA 전 로그인 수정

---

src/api/FileAPI.ts
src/components/Alarm/index.tsx
src/components/Common/Header/index.tsx
src/components/GlobalModal/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/components/MatchPost/PostLabel/index.tsx
src/components/MatchPost/PostReplySection/index.tsx
src/components/Matching/FilterButton/index.tsx
src/components/Matching/SearchBar/index.tsx
src/components/Matching/SearchBar/styles.ts
src/hooks/useLoginInfo.tsx
src/pages/Main/index.tsx
src/pages/MatchPost/index.tsx
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/OtherProfile/index.tsx
src/recoil/atom/LoginInfoState.ts

Refactor: Accesstoken Bearer설정

---

src/api/FileAPI.ts
src/components/Alarm/Invitation/index.tsx
src/components/Alarm/index.tsx
src/components/Common/Header/index.tsx
src/components/GlobalModal/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/components/MatchPost/PostLabel/index.tsx
src/components/MatchPost/PostReplySection/index.tsx
src/components/Matching/FilterButton/index.tsx
src/components/Matching/SearchBar/index.tsx
src/components/Matching/SearchBar/styles.ts
src/hooks/useLoginInfo.tsx
src/pages/Main/index.tsx
src/pages/MatchPost/index.tsx
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/OtherProfile/index.tsx
src/recoil/atom/LoginInfoState.ts

Feat/매칭 수락,거절 CTA 추가

---

package-lock.json
package.json
src/components/GlobalModal/expireTest.ts
src/components/GlobalModal/index.tsx
src/components/MatchPost/PostArticle/index.tsx
src/components/MatchPost/PostLabel/index.tsx
src/components/MatchPost/PostReplySection/index.tsx
src/components/MatchPost/PostStateModal/index.tsx
src/components/Matching/FilterButton/index.tsx
src/components/Matching/MatchingContainer/index.tsx
src/hooks/MatchingPost/usePostMatchingArticleLikeMutation.ts
src/hooks/MatchingPost/usePostReplyLikeMutation.ts
src/hooks/MatchingPost/useUpdateCombo.ts
src/hooks/MatchingPost/useUpdateMatchingStatusCancle.ts
src/pages/Main/index.tsx
src/pages/MatchPost/index.tsx
src/pages/OtherProfile/index.tsx

1. 글로벌 모달 3일간 열지 않기 로직 및 UI 추가
2. 글로벌 모달 렌더링 로직 최적화
3. 매칭메인 게시글 관람일 css 어긋남 현상 수정
4. 좋아요 버튼 유효성 로직 추가 
<br/>
>X
<br/>
>X
<br/>
> X
<br/>
>X

QA: 글로벌 모달 로직 및 기타 수정 (1030)

---

src/components/GlobalModal/index.tsx
src/components/Matching/FilterButton/index.tsx
src/components/OtherProfile/ImageCarousel/index.tsx
src/components/OtherProfile/ImageCarousel/styles.ts
src/pages/Main/index.tsx
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/OtherProfile/index.tsx
src/pages/Posting/PutPosting/index.tsx

1. 타인프로필 이미지 수정  (subimgs값이 null값이어서 백엔드 확인 필요 ,정상 응답시 렌더되게 작성해둠)
2. 로그인 안한 유저 매칭메인 게시글작성 버튼 클릭시 alert창 대신 로그인창 뜨도록 UX개선
3. 매칭메인 글로벌모달 삭제 (새로고침시 UX 저하 및 초기 렌더시간 증가 문제로 삭제, UX개선 )
4. 글로벌모달 opacity 0->1 애니메이션 추가, UX개선 
<br/>
<br/>
<br/>
<br/>

QA: 타인프로필 이미지캐러셀 수정 및 기타 리팩터 (QA1101)

---

src/components/Alarm/Accept/index.tsx
src/components/Alarm/Accept/styles.ts
src/components/Alarm/Comment/index.tsx
src/components/Alarm/Comment/styles.ts
src/components/Alarm/CommentHeart/index.tsx
src/components/Alarm/CommentHeart/styles.ts
src/components/Alarm/Event/index.tsx
src/components/Alarm/Event/styles.ts
src/components/Alarm/Invitation/index.tsx
src/components/Alarm/Invitation/styles.ts
src/components/Alarm/Recomment/index.tsx
src/components/Alarm/Recomment/styles.ts
src/components/Alarm/Refuse/index.tsx
src/components/Alarm/Refuse/styles.ts
src/components/Alarm/Remind/index.tsx
src/components/Alarm/Remind/styles.ts
src/components/Alarm/Report/index.tsx
src/components/Alarm/Report/styles.ts
src/interfaces/Alarm/IAlarm.ts
src/recoil/atom/AlarmCount.ts

<br/>
> 알림 읽지 않았다면 #5E1EC7 로 글씨 렌더링
<br/>
<br/>
<br/>

Refactor/ 읽음 여부 처리에 따른 알림 개수 및 UI 변동

---

src/components/Alarm/Openchat/index.tsx
src/components/Alarm/Openchat/styles.ts

style: 알림 읽음 처리 추가

---

src/api/FileAPI.ts
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx

feat: 프로필 수정 이미지 에러 이슈 해결

---

src/pages/MyProfile/PutMyProfile/index.tsx

feat: mainImg가 subImg[0]에 포함되도록 수정

---

src/components/MatchPost/PostArticle/index.tsx
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/Posting/PutPosting/index.tsx

feat: 게시글 내부 이미지 이슈 해결

---

src/components/Common/Header/index.tsx
src/components/OtherProfile/ImageCarousel/index.tsx
src/pages/OtherProfile/index.tsx

feat: 타인프로필 이미지 에러 해결 로직 반영

---

src/App.tsx
src/components/Common/Header/index.tsx
src/components/GlobalModal/expireTest.ts
src/components/GlobalModal/index.tsx
src/components/Login/GoogleRedirectHandler/index.tsx
src/components/MatchPost/PostArticle/index.tsx
src/components/MatchPost/PostLabel/index.tsx
src/components/MatchPost/PostReplySection/index.tsx
src/components/Matching/MatchingContainer/index.tsx
src/components/Matching/MatchingContainer/styles.ts
src/pages/Matching/index.tsx
src/pages/OtherProfile/index.tsx

* fix: 3일간 열지 않기 기능 동작 오류 수정
* refactor: 리액트쿼리 devtools 개발모드일 때만 보이도록 수정
* refactor: suspense 컴포넌트 리팩터
* fix: 모집 중이 아닌 게시글에 댓글 작성 불가로 수정
* feat: 게시글 모집상태 background css 구분 추가
* chore: 게시글 모집 취소 alert문구 수정
* fix: FsLightBox 컴포넌트 버그 수정
<br/>
<br/>
<br/>
<br/>

QA: 라이트박스,모달창 버그 해결 (#90)

---

src/App.tsx
src/components/MatchPost/PostArticle/index.tsx
src/components/OtherProfile/ImageCarousel/index.tsx
src/components/OtherProfile/ImageCarousel/styles.ts
src/pages/MyProfile/PostMyProfile/index.tsx
src/pages/MyProfile/PutMyProfile/index.tsx
src/pages/OtherProfile/index.tsx
src/pages/OtherProfile/styles.ts

QA:  타인프로필 이미지 캐러셀 로직,UI 수정
